####Pandas Notes

The idea in this notebook is to create a summary of Pandas commands that I took from either QLX-I master and internet
;-)

In [0]:
#Import libraries
import pandas as pd
import numpy as np

In [0]:
# to read data from URL
ufo = pd.read_table('http://bit.ly/uforeports', sep=',')

In [0]:
ufo.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [0]:
# to read only one column
ufo['State']

0        NY
1        NJ
2        CO
3        KS
4        NY
         ..
18236    IL
18237    IA
18238    WI
18239    WI
18240    FL
Name: State, Length: 18241, dtype: object

In [0]:
#concatenate
ufo['Location']=ufo.City + ', ' + ufo.State
ufo.head()

                   City  ...                  Location
0                Ithaca  ...                Ithaca, NY
1           Willingboro  ...           Willingboro, NJ
2               Holyoke  ...               Holyoke, CO
3               Abilene  ...               Abilene, KS
4  New York Worlds Fair  ...  New York Worlds Fair, NY

[5 rows x 6 columns]

In [0]:
# to see the number of rows
ufo.shape

(18241, 6)

In [0]:
# to see the data type
ufo.dtypes

City               object
Colors Reported    object
Shape Reported     object
State              object
Time               object
Location           object
dtype: object

In [0]:
# to see the columns
ufo.columns

Index(['City', 'Colors Reported', 'Shape Reported', 'State', 'Time',
       'Location'],
      dtype='object')

In [0]:
# to delete a column 
ufo.drop('Colors Reported', axis=1, inplace=True)
ufo.head()

                   City  ...                  Location
0                Ithaca  ...                Ithaca, NY
1           Willingboro  ...           Willingboro, NJ
2               Holyoke  ...               Holyoke, CO
3               Abilene  ...               Abilene, KS
4  New York Worlds Fair  ...  New York Worlds Fair, NY

[5 rows x 5 columns]

In [0]:
#to sort
ufo.State.sort_values(ascending=False).head()

12079    WY
11490    WY
11333    WY
4866     WY
3326     WY
Name: State, dtype: object

##Series

In [0]:
# creamos unas etiquetas
etiquetas=['a','b','c']
datos=[1,2,3]
pd.Series(data=datos, index=etiquetas)

a    1
b    2
c    3
dtype: int64

In [0]:
# lo creamos a partir de un array
array=np.arange(0,3)
etiqueta=['venta1','venta2','venta3']
serie1= pd.Series(array, etiqueta)
serie1

venta1    0
venta2    1
venta3    2
dtype: int64

In [0]:
serie1['venta1'] #acceder directamente por etiqueta
serie1[2] #accesamos por posicion

2

In [0]:
datos2=['Informatica',300,'impresora',400] #Series con diferentes valores
pd.Series(datos2)

0    Informatica
1            300
2      impresora
3            400
dtype: object

In [0]:
#Sumando series
serie1=pd.Series([1,2,3],['ventas1','ventas2','ventas3'] )
serie2=pd.Series([4,8,5],['ventas1','ventas2','ventas3'] )
serie_suma=serie1 + serie2
serie_suma

ventas1     5
ventas2    10
ventas3     8
dtype: int64

##DataFrames

In [0]:
filas=['ventas1','ventas2','ventas3']
columnas=['zonaA','zonaB','zonaC']
datos=[[123,421,256],[234,541,257],[120,451,258]]
dataframe=pd.DataFrame(datos,filas,columnas)
dataframe

         zonaA  zonaB  zonaC
ventas1    123    421    256
ventas2    234    541    257
ventas3    120    451    258

In [0]:
#seleccionamos la primera fila
dataframe.loc['ventas1']

zonaA    123
zonaB    421
zonaC    256
Name: ventas1, dtype: int64

In [0]:
dataframe.loc[['ventas1','ventas3']]

         zonaA  zonaB  zonaC
ventas1    123    421    256
ventas3    120    451    258

In [0]:
#por columna
dataframe['zonaA']

ventas1    123
ventas2    234
ventas3    120
Name: zonaA, dtype: int64

In [0]:
#Varias columnas
dataframe[['zonaA', 'zonaC']]

         zonaA  zonaC
ventas1    123    256
ventas2    234    257
ventas3    120    258

In [0]:
#seleccionar por valor
dataframe.loc['ventas1']['zonaA']

123

In [0]:
#Creando una nueva columna
dataframe['Todaszonas']=dataframe['zonaA']+dataframe['zonaB']+dataframe['zonaC']
dataframe

         zonaA  zonaB  zonaC  Todaszonas
ventas1    123    421    256         800
ventas2    234    541    257        1032
ventas3    120    451    258         829

In [0]:
#para borrar la columna en la vizualization
dataframe.drop('Todaszonas', axis=1)

         zonaA  zonaB  zonaC
ventas1    123    421    256
ventas2    234    541    257
ventas3    120    451    258

In [0]:
#para borrar la columna definitivamente
dataframe.drop('Todaszonas', axis=1, inplace=True)
dataframe

         zonaA  zonaB  zonaC
ventas1    123    421    256
ventas2    234    541    257
ventas3    120    451    258

In [0]:
#Borrar una fila
dataframe.drop('ventas3')

         zonaA  zonaB  zonaC
ventas1    123    421    256
ventas2    234    541    257

In [0]:
#para ver la estructura (cuantas filas y cuantas columnas)
dataframe.shape

(2, 3)

Seleccion de datos con condicion

In [0]:
filas='ventas1 ventas2 ventas3'.split() #otra foema de crear los valores
columnas='zonaA zonaB zonaC'.split()
datos=[[120,340,250],[210,450,250],[310,210,140]]

In [0]:
#creamos el dataframe
dataframe=pd.DataFrame(datos,filas,columnas)
dataframe

         zonaA  zonaB  zonaC
ventas1    120    340    250
ventas2    210    450    250
ventas3    310    210    140

In [0]:
#condicion
condicion=dataframe>200
#utilizamos la condicion para extraer datos
dataframe[condicion]

         zonaA  zonaB  zonaC
ventas1    NaN    340  250.0
ventas2  210.0    450  250.0
ventas3  310.0    210    NaN

In [0]:
#por condicion dentro de una columna
condicion=dataframe['zonaA'] > 200
dataframe[condicion]

         zonaA  zonaB  zonaC
ventas2    210    450    250
ventas3    310    210    140

In [0]:
# creando condicion dobles
condicion= (dataframe['zonaA'] > 200) & (dataframe['zonaB'] > 300)
dataframe[condicion]

         zonaA  zonaB  zonaC
ventas2    210    450    250

In [0]:
#ahora aplicamos la condicion anterios pero en una columna determinada
dataframe[condicion]['zonaB']

ventas2    450
Name: zonaB, dtype: int64

In [0]:
#en varias columnas
dataframe[condicion][['zonaB','zonaC']]

         zonaB  zonaC
ventas2    450    250

In [0]:
dataframe

         zonaA  zonaB  zonaC
ventas1    120    340    250
ventas2    210    450    250
ventas3    310    210    140

In [0]:
#cambiamos los nombres de las filas
nuevas_filas='dia1 dia2 dia3'.split()
dataframe['dias']=nuevas_filas

In [0]:
dataframe

         zonaA  zonaB  zonaC  dias
ventas1    120    340    250  dia1
ventas2    210    450    250  dia2
ventas3    310    210    140  dia3

In [0]:
#ahora se pasa esa columa al index para cabiar el nombre de filas
dataframe.set_index('dias')

      zonaA  zonaB  zonaC
dias
dia1    120    340    250
dia2    210    450    250
dia3    310    210    140

In [0]:
#para ejecutarlo de forma permanente
dataframe=dataframe.set_index('dias')
dataframe

      zonaA  zonaB  zonaC
dias
dia1    120    340    250
dia2    210    450    250
dia3    310    210    140

In [0]:
#creamos un dataframe a partir de un diccionario
diccionario={'A':[4,5,np.nan], 'B': [6,1,5], 'C': [np.nan,4,np.nan]}
dataframe=pd.DataFrame(diccionario)
dataframe

     A  B    C
0  4.0  6  NaN
1  5.0  1  4.0
2  NaN  5  NaN

In [0]:
#Para borrar los nulos    OJO---- borra cualquier fila donde este nulo
dataframe.dropna()

     A  B    C
1  5.0  1  4.0

In [0]:
dataframe.dropna(axis=1)
#con inplace lo ejecuta definitivamente

   B
0  6
1  1
2  5

In [0]:
#para rellenar los valores nulos con algun valor
dataframe.fillna(value=100)

       A  B      C
0    4.0  6  100.0
1    5.0  1    4.0
2  100.0  5  100.0

In [0]:
#o rellenarlo con el valor medio
valor_medio=dataframe.mean()
dataframe.fillna(value=valor_medio)

     A  B    C
0  4.0  6  4.0
1  5.0  1  4.0
2  4.5  5  4.0

##Agrupacion de los datos

In [0]:
#creamos el dataframe:
diccionario={'dias':['dia1','dia1','dia2','dia2','dia3'], 'vendedores': ['Antonio', 'Maria', 'Jose', 'Maria', 'Juan'], 'ventas': [100,400,200,500,300]}
dataframe=pd.DataFrame(diccionario)
dataframe

   dias vendedores  ventas
0  dia1    Antonio     100
1  dia1      Maria     400
2  dia2       Jose     200
3  dia2      Maria     500
4  dia3       Juan     300

In [0]:
dataframe.groupby('dias').sum()

      ventas
dias
dia1     500
dia2     700
dia3     300

In [0]:
#para recrear unas estadisticas
dataframe.groupby('dias').describe()

     ventas
      count   mean         std    min    25%    50%    75%    max
dias
dia1    2.0  250.0  212.132034  100.0  175.0  250.0  325.0  400.0
dia2    2.0  350.0  212.132034  200.0  275.0  350.0  425.0  500.0
dia3    1.0  300.0         NaN  300.0  300.0  300.0  300.0  300.0

Esta seccion solo son comentarios acerca de lo que hace el comando

In [0]:
# para hacer una UNION se hace con concat 

#pd.concat([dataframe1,dataframe2]) # usando filas
#pd.concat([dataframe1,dataframe2], axis=1) # usando Columnas

#Para hacer un Merge   En este caso usamos los campos Key o comunes de ambas tablas
#pd.merge(dataframe1,dataframe2, on="clave key")

#Join entre dos datasets
#dataframe.join(dataframe2)

#Leer archivos csv

#dataframe=pd.read_excel('Ejemplo.xlsx')

#Para escribir o exportar a excel.
#dataframe.to_excel('Ejemplo.xlsx', sheet_name='Hoja1')

###Operaciones con DataFrame

In [0]:
#para sacar los valores unicos de un dataframe

diccionario={'A': [11,12,10,12], 'B': [14,18,16,17]}
dataframe=pd.DataFrame(diccionario,index=['i1', 'i2', 'i3', 'i4'])
dataframe
#dataframe['columna'].unique() # solo saca los valores que no se repiten

#para generar un count

     A   B
i1  11  14
i2  12  18
i3  10  16
i4  12  17

In [0]:
dataframe['A'].value_counts()

12    2
11    1
10    1
Name: A, dtype: int64

In [0]:
#Usamos una funcion para hacer operaciones con esta

#definimos la funcion

def multiplicar(x):
  return x*2

dataframe['A'].apply(multiplicar)

i1    22
i2    24
i3    20
i4    24
Name: A, dtype: int64

In [0]:
#usamos la funcion lambda
dataframe['A'].apply(lambda x: x*2)

i1    22
i2    24
i3    20
i4    24
Name: A, dtype: int64